-- Payment requests table for cross-device wallet payments
-- ID is the saleId generated by the POS (text, not UUID)
create table if not exists public.payment_requests (
    id text primary key,
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    client_id uuid references public.clients(id) on delete set null,
    amount numeric(12,2) not null default 0,
    items jsonb default '[]',
    status text not null default 'pending' check (status in ('pending','confirmed','rejected','expired','cancelled')),
    pin text,
    metadata jsonb default '{}',
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    expires_at timestamptz
);

-- Index for fast lookups by client + status
create index if not exists idx_payment_requests_client_status 
    on public.payment_requests(client_id, status, created_at desc);

-- Index for tenant lookups
create index if not exists idx_payment_requests_tenant 
    on public.payment_requests(tenant_id, created_at desc);

-- Trigger to auto-update updated_at
 create or replace function public.set_updated_at()
 returns trigger as $$
 begin
     new.updated_at = now();
     return new;
 end;
 $$ language plpgsql;

 drop trigger if exists set_payment_requests_updated_at on public.payment_requests;
 create trigger set_payment_requests_updated_at
     before update on public.payment_requests
     for each row
     execute function public.set_updated_at();

-- RLS disabled for simplicity: clients authenticate by PIN (not Supabase Auth)
-- In production, consider an Edge Function for confirmation instead.
 alter table public.payment_requests disable row level security;
